import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Button } from '@mui/material';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import Chart from 'chart.js/auto'; // Import Chart.js for creating charts

import './clientLedgerPage.css'; // Import custom styles

const ClientLedgerPage = () => {
  const [clientNames, setClientNames] = useState([]);
  const [selectedClient, setSelectedClient] = useState('');
  const [keyword, setKeyword] = useState('');  // User-defined keyword
  const [limit, setLimit] = useState(10);  // Default limit is 10
  const [clientLedger, setClientLedger] = useState([]);  // To store selected client ledger data
  const [summary, setSummary] = useState(null);  // To store the summary data
  const [loading, setLoading] = useState(false);

  const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
  const ADMIN_ACCESS_TOKEN = localStorage.getItem("adminToken") || import.meta.env.VITE_ADMIN_ACCESS_TOKEN;

  // Fetch all client names based on keyword and limit
  useEffect(() => {
    const fetchClients = async () => {
      try {
        setLoading(true);
        const response = await axios.get(`${API_BASE_URL}admin/client-ledger/user`, {
          headers: { Authorization: `Bearer ${ADMIN_ACCESS_TOKEN}` },
          params: {
            keyword: keyword || undefined,  // Use undefined if keyword is empty
            limit: limit || 10,  // Default to 10 if limit is not provided
          },
        });
        setClientNames(response.data.data);
      } catch (error) {
        console.error('Error fetching client names:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchClients();
  }, [keyword, limit]); // Trigger the effect when keyword or limit changes

  // Fetch client ledger data when selectedClient changes
  useEffect(() => {
    if (selectedClient) {
      const fetchClientLedger = async () => {
        try {
          setLoading(true);
          const response = await axios.get(`${API_BASE_URL}admin/client-ledger`, {
            headers: { Authorization: `Bearer ${ADMIN_ACCESS_TOKEN}` },
            params: { clientName: selectedClient },
          });

          // Set the client ledger and summary data
          setClientLedger(response.data.data);
          setSummary(response.data.meta.summary);
        } catch (error) {
          console.error('Error fetching client ledger:', error);
        } finally {
          setLoading(false);
        }
      };

      fetchClientLedger();
    }
  }, [selectedClient]);

  const generatePDF = () => {
    const doc = new jsPDF();
    const softGray = [169, 169, 169];  // Light gray for non-important text
    const softBlue = [100, 149, 237];  // Soft blue for the "Thank You" text
    const softGreen = [34, 139, 34];   // Soft green for the contact number
    const softRed = [255, 99, 132];    // Soft red for the email

    // Add Company Logo - Center the logo at the top of the PDF
    const logoWidth = 40;
    const logoHeight = 20;
    const logoX = (doc.internal.pageSize.width - logoWidth) / 2;
    doc.addImage('/AAS.jpeg', 'jpeg', logoX, 10, logoWidth, logoHeight); // Center the logo

    // Add Report Title
    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235); // Blue color for title
    doc.text(`Ledger Report For Mr. ${selectedClient}`, (doc.internal.pageSize.width - 100) / 2, 40);  // Center the title

    // Add some spacing below the title
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold'); // Make company details bold
    doc.setTextColor(0, 0, 0); // Black color for text
    doc.text('Generated by: ASIA AGRO SILAGE & SERVICES', (doc.internal.pageSize.width - 100) / 2, 50);  // Centered text

    // Add Company Details - Bolded and with more space
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold'); // Make company details bold
    doc.text('Address: Asia agro silage main bypass road, Kasur', 14, 70);
    doc.text('Date: ' + new Date().toLocaleDateString(), 14, 80);

    // Add some more spacing before the summary section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');

    // Add the Summary Data to the PDF with a card-like layout
    if (summary) {
      // Set fill color for cards (blue for summary background)
      doc.setFillColor(...softGray);  // Blue color for background

      // Draw the summary box for background
      doc.rect(10, 95, 190, 45, 'F'); // Summary card background color

      // Add 'Summary' heading with bold white text
      doc.setTextColor(0, 0, 0); // White text color for heading
      doc.setFont('helvetica', 'bold');
      doc.text('Summary', 14, 105);  // Center the heading

      // Set the text color to black for the summary items
      doc.setTextColor(0, 0, 0); // White text color for summary items
      doc.setFont('helvetica', 'normal');

      // Add Summary Items (Total Amount, Total Paid, etc.)
      doc.text(`Total Amount: ${summary.totalAmount}`, 14, 115);
      doc.text(`Total Paid: ${summary.totalAmountPaid}`, 14, 120);
      doc.text(`Total Discount: ${summary.totalDiscount}`, 14, 130);
      doc.setFont('helvetica', 'bold');
      // Highlight "Total Remaining" with red color
      doc.setTextColor(255, 99, 132);  // Red color for "Remaining"
      doc.text(`Total Remaining:`, 14, 125);  // Label for remaining
      doc.text(`${summary.totalRemainingAmount}`, 60, 125);  // Remaining amount in red color
    }



    // Table Header with Styling
    const tableData = clientLedger.map((entry) => [
      entry.billNo,
      entry.noOfBales,
      entry.weightinKgs,
      entry.pricePerKg,
      entry.discount,
      entry.totalAmount,
      entry.amountPaid,
      entry.remainingAmount,
    ]);

    // Table Styling with enhanced formatting
    doc.autoTable({
      head: [
        [
          'Bill No',
          'No Of Bales',
          'Weight in Kgs',
          'Price Per Kg',
          'Discount',
          'Total Amount',
          'Amount Paid',
          'Remaining Amount'
        ],
      ],
      body: tableData,
      startY: 150,
      styles: {
        fontSize: 10,
        cellPadding: 5,
        halign: 'center',
        fillColor: [255, 255, 255], // White background for table rows
      },
      headStyles: {
        fillColor: [37, 99, 235],  // Blue background for table header
        textColor: [255, 255, 255], // White text color in header
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [240, 240, 240],  // Light grey for alternate rows
      },
      margin: { top: 10 },
    });

    // Add some spacing before the Download Button
    doc.setFontSize(12);

    // Soft colors for the footer


    // Add Generated On Text with a soft gray color
    doc.setTextColor(...softGray); // Set a soft gray color for the date
    doc.text('Generated on: ' + new Date().toLocaleDateString(), 14, doc.lastAutoTable.finalY + 10);

    // Add Thank You Message with a soft blue color
    doc.setFont('helvetica', 'bold');  // Make "Thank you" text bold
    doc.setTextColor(...softBlue);  // Soft blue color for the "Thank You" message
    doc.text('Thank you for using Asia Agro Silage & Services!', 14, doc.lastAutoTable.finalY + 20);

    // Add Contact Details with soft green for the contact number
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...softGreen); // Soft green color for the contact number
    doc.text('Contact us at: +92-303-001919 / +92-326-0017919 / +92-300-6598685', 14, doc.lastAutoTable.finalY + 30);

    // Add Email Text with a soft red color
    doc.setTextColor(...softRed); // Soft red color for the email
    doc.text('Email: info@asiaagrosilage.com', 14, doc.lastAutoTable.finalY + 40);

    // Center-align the copyright text
    doc.setTextColor(...softGray);  // Light gray for the copyright text
    const copyrightText = '© 2024 Asia Agro Silage & Services. All rights reserved.';
    const textWidth = doc.getTextWidth(copyrightText);  // Get the width of the text to center it
    const pageWidth = doc.internal.pageSize.width;  // Get the page width
    const xPosition = (pageWidth - textWidth) / 2;  // Calculate the X position to center the text
    doc.text(copyrightText, xPosition, doc.lastAutoTable.finalY + 70);  // Centered copyright


    // Save the PDF with a name
    doc.save(`client_ledger_report_${selectedClient || 'all'}.pdf`);
  };

  return (
    <div className="client-ledger-page">
      <h1>Client Ledger</h1>

      {/* Input fields for Keyword and Limit */}
      <div className="input-fields">
        <div>
          <label>Keyword:</label>
          <input
            type="text"
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}  // Update the keyword state
            placeholder="Enter keyword"
          />
        </div>

        <div>
          <label>Limit:</label>
          <input
            type="number"
            value={limit}
            onChange={(e) => setLimit(Number(e.target.value))}  // Update the limit state
            placeholder="Enter limit"
          />
        </div>
      </div>

      {/* Client Selection */}
      <div className="client-selection">
        <select onChange={(e) => setSelectedClient(e.target.value)} value={selectedClient}>
          <option value="">Select Client</option>
          {clientNames.map((client) => (
            <option key={client.clientName} value={client.clientName}>
              {client.clientName}
            </option>
          ))}
        </select>
      </div>

      {loading ? (
        <p>Loading...</p>
      ) : (
        <div>
          {/* Download Button */}
          <Button
            style={{ display: 'block', margin: '0 auto' }}
            onClick={generatePDF}
            variant="contained"
            color="primary"
          >
            Download Ledger as PDF
          </Button>

          <br></br>
          <br></br><br></br>

          {/* Show the summary using the new summary-cards layout */}
          {summary && (
            <div className="summary-cards">
              <div>
                <h4>Total Amount</h4>
                <span>{summary.totalAmount}</span>
              </div>
              <div>
                <h4>Total Paid</h4>
                <span>{summary.totalAmountPaid}</span>
              </div>
              <div>
                <h4>Total Remaining</h4>
                <span>{summary.totalRemainingAmount}</span>
              </div>
              <div>
                <h4>Total Discount</h4>
                <span>{summary.totalDiscount}</span>
              </div>
            </div>
          )}

          {/* Client Ledger Table */}
          {clientLedger.length > 0 ? (
            <table className="client-ledger-table">
              <thead>
                <tr>
                  <th>Bill No</th>
                  <th>No Of Bales</th>

                  <th>Weight in Kgs</th>
                  <th>Price Per Kg</th>
                  <th>Discount</th>

                  <th>Total Amount</th>
                  <th>Amount Paid</th>
                  <th>Remaining Amount</th>
                </tr>
              </thead>
              <tbody>
                {clientLedger.map((entry) => (
                  <tr key={entry._id}>
                    <td>{entry.billNo}</td>
                    <td>{entry.noOfBales}</td>
                    <td>{entry.weightinKgs}</td>
                    <td>{entry.pricePerKg}</td>
                    <td>{entry.discount}</td>
                    <td>{entry.totalAmount}</td>
                    <td>{entry.amountPaid}</td>
                    <td>{entry.remainingAmount}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <p>No data available for the selected client.</p>
          )}


        </div>
      )}
    </div>
  );
};

export default ClientLedgerPage;
